### ISSUE TITLE
Typo: isSameSiteNoneCompactible should be isSameSiteNoneCompatible

### ISSUE THREAD

**Issue by syuraj** [linsight/should-send-same-site-none#1]
https://github.com/linsight/should-send-same-site-none/blob/d263fa22cd69b9879c12d7f63fe9fd5cd5e0066c/index.js#L139

**Comment by dlin-me** [comment]
@syuraj  Thank you for reporting.

NPM has the recent updates but  I forgot pushing the fixes 2.0.1 and 2.0.2 to Github.

I've just pushed the two missing patch versions to Github.
