### ISSUE TITLE
isSameSiteNoneCompatible(falsey values) is evaluated to true

### ISSUE THREAD

**Issue by nsunga** [linsight/should-send-same-site-none#4]
isSameSiteNoneCompatible(falsey values) is evaluated to true. Is this the right behavior for this case?

Falsey values I tried: null, undefined, 0, false, and empty string.

**Comment by dlin-me** [comment]
This is known behavior. Not only false values, if you pass some strange value like `foo` it will return `true`, too. The function means to detect incompatible user-agent strings using pattern matchings, but it will not validate the string being valid or not. 

I think it will sound better if the  function is named `isSameSiteNoneIncompatible` and return false for `foo`  and `false` parameter.   However,  it doesn't help much.
